TRUTH = (
    "Pernahkah Kamu Ghosting Seseorang ?"
    "Sebutkan Hal - Hal Apa Saja Yang Membosankan Bagimu ?",
    "Siapa Mantan Terindahmu ? Mengapa ?",
    "Kalau Kamu Suka Ke Seseorang Apa Yang Akan Kamu Lakukan ?",
    "Jika Kamu Harus Memilih, Sahabat Atau Tunangan ?",
    "Siapa Orang Di Grup Yang Kamu Tidak Suka ? Mengapa ?",
    "Berikan Pendapatmu Terhadap Orang Yang sedang Bermain Sekarang.",
    "Sebutkan 3 Hal Dari Sahabatmu Yang Membuatmu Jengkel.",
    "Jelaskan Tentang Dirimu.",
    "Ceritakan Pengalaman Gabung Grup Ini.",
    "Kapan Terakhir Kali Kamu Berbohong Kepada Orang Tua, Mengapa ?.",
    "Jelaskan Seperti Apa Pria/Wanita Yabg Kamu Suka.",
    "Apakah Rahasiamu Saat Ini Yang Tidak Diketahui Orang Lain ?.",
    "Pernahkan Kamu Terbalik Pakai Pakaian, Mengapa ?.",
    "Sebutkan Impianmu Saat Ini ?.",
    "Adakah Orang Yang Kamu Suka Di Grup Ini ? mengapa ?.",
    "Kalau Orang Yang Kamu Suka Ada Di Depanmu Apa Yang Kamu Lakukan ?.",
    "Spill Nama Gebetan Kamu Sekarang.",
    "Udah Move On Belum Dari Mantan ?.",
    "Siapa Mantan Yang Paling Lama Kamu Pacarin ?.",
    "Apa Kenangan Bersama Mantan Yang Paling Indah ?.",
)

DARE = (
    "Foto Dirimu Sekarang Dan Kirim Ke Orang Yang Kamu Benci. (Foto Paling Menjengkelkan)."
    "Telpon Owner Grup Dan Katakan Hal Yang Membuatnya Tertawa.",
    "Buat Vidio Tiktok Dan Upload.",
    "Makan Nasi Tanpa Lauk Sebanyak 5 Suapan Di Depan Mantan. Dan Katakan Rasanya Hambar.",
    "Push Up 10x Sambil Berkata 'Aku Sayang Kamu, Mantan'.",
    "Nyanyikan Lagu Nina Bobo Di Depan Orang Banyak Dan Suruh Mereka Tidur.",
    "Pilih Salah Satu Admin Dan Buat Dia Marah.",
    "Lakukan Tari Tortor Sambil Berikan Pantun Ke Salah Seorang Pemain.",
    "Pasang Foto Profile Sesuai Permintaan Pemain Lain.",
    "Chat Mantan Dan Katakan Sesuai Keinginan Pemain Lain.",
    "Nyanyikan Lagu China",
    "Pakai Helm Atau Topi Dan Jaipongan",
    "Like Status dan Foto Mantan Di Akun Medsosnya",
    "Makan Garam Dan Katakan Manis Kepada Orang Banyak.",
    "Pergi Ke Warung Terdekat Dan Tanyakkan Apakah Mantanku Masih Hidup ?.",
    "Buatlah Pemain Lain Tertawa Terbahak-Bahak.",
    "Katakan Sekarang 'Aku Sayang Kamu' Pada (Dipilih Pemain Lain).",
    "Makanlah Sesuatu Dan Bagikan Baunya dari Mulut Ke Orang Banyak.",
    "Tunjukkan Jumlah Uang Di Dompet/Akun Bankmu.",
    "Traktik Salah Satu Pemain.",
    "Tahan Nafas Lebih Lama Dari Pemain Lain.",
    "Makanlah Sesuatu Tanpa Menggunakan Tangan.",
    "Rayu dan Bersikap Mesralah Kepada Seorang Lawan Jenismu Selama 3 Hari. (Ditentukan Pemain Lain)",
    "Buka 3 Rahasia Sahabatmu.",
    "Telpon Salah Satu Lawan Jenis Di Grup Dan Berikan Suara Kiss Kepadanya (Tanpa Bilang Dare).",
    "Pasang Foto Mantan Sebagai Foto Profile Wa dan Telegram Selama 3 Hari (Jangan Privasi).",
    "Minum Kopi Atau Teh Tanpa Gula.",
    "Coba Sentuh Hidungmu Dengan Lidah Sampai Temanmu Tertawa (Kalau Belum Tertawa Lakukan Terus).",
    "Berenanglah Dilantai/Tanah Didepan Orang Banyak.",
    "Buat Status Tentang Mantan.",
    "Pergi Ke Keramaian Dan Bilang 'Saya Gila, Saya Gila, Saya Gila'.",
    "Lakukan Salah Satu Dance Tiktok Di depan Orang Banyak.",
    "Tanyakkan Pemain Lain Tantangan Untukmu.",
    "Telepon Mantan Dan Minta Dia Memberikan Truth Untukmu.",
    "Telepon Mantan Dan Minta Dia Memberkan Dare Untukmu.",
    "Tunjukkan Riwayat Telpon atau Vidio Callmu.",
    "Tunjukkan Foto Tercantikmu Ke Mantan.",
    "Ajak Mantan Balikan",
    "Ajak Orang Lain Siapapun Melakukan Selfie Denganmu.",
    "Tunjukkan 5 Chat Terakhirmu.",
    "Ungkapkan Rasa Terimakasih Ke Orang Tua Buat Selama Ini.",
    "Pergi Keluar Rumah Dan Masuk Lagi Selama 3x.",
    "Tanyakkan Ke Owner Grup Untuk Daremu.",
    "Nyanyikan Sebuah Lagu.",
    "Tirukan Ketawa Kuntilanak Di Depan Banyak Orang.",
    "Kenakan Sesuatu Di Kepalamu dan Lakukan Gerakan Pocong Melompat.",
    "Teriakkan Nama Orang Yang Kamu Suka Di Depan Orang Banyak.",
    "Tunjukkan Kenanganmu Dulu Bersama Semua Mantan.",
    "Minum Air Putih Dan Tahan Sampai 2 Putaran.",
    "Tanyakkan Daremu Ke Salah Satu Pemain..",
    "Telfon Mantan Dan Bilang 'AKU BELUM BISA MOVE ON DARI KAMU'.",
    "Kirim Pap Muka Jelek Ke Orang Yang Ada Di Kontak WA",
    "Posting Status Whatsapp Foto Sama Mantan Dulu.",
)
